FROM ghcr.io/reconcycle/gzweb:latest

RUN git clone https://github.com/ReconCycle/franka_panda_description ~/gzweb/http/client/assets/franka_panda_description

LABEL org.opencontainers.image.source=https://github.com/ReconCycle/dockers
