version: '3'

networks:
  ros:
    driver: bridge

services:

  # roscore
  rosmaster:
    image: ros:kinetic
    command: stdbuf -o L roscore
    networks:
      - ros
    environment:
      - "ROS_HOSTNAME=rosmaster"
      
  # novnc @ localhost:8080
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8081:8080"
    networks:
      - ros
  
  # rviz
  rviz:
    image: ghcr.io/reconcycle/reconcycle-simulation:kinetic
    depends_on:
      - rosmaster
    #command: stdbuf -o L roslaunch --wait reconcycle_description display_sim.launch
    command: stdbuf -o L rviz
    environment:
      - "DISPLAY=novnc:0.0"
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - "ROS_HOSTNAME=rviz"
    networks:
      - ros
    restart: always
  
  #layout manager
  layout:
    image: ghcr.io/reconcycle/reconcycle-cell-visualization:kinetic
    command: stdbuf -o L roslaunch --wait vision_ros_integration vp_data_launch.launch
    environment:
      - "ROS_MASTER_URI=http://10.20.0.1:11311"
      - "ROS_IP=10.20.0.1"
      - "DISPLAY=novnc:0.0"
    networks:
      - ros
    restart: always
